### PR TITLE
TST/BUG: Save model as netcdf, file for pysatModels, bugs in unit tests

### LINKED ISSUE #115: TST/BUG: Improve load_data test robustness
**Describe the bug**
Currently both of the data load tests use two time steps.  This can mask array dimensional errors if the wrong dimension also happens to have two values.  See #114.

**Proposed Solution**
Use 2 time steps for formatted, 3 for unformatted.  This way we do test that routines work with an arbitrary number of time steps.  Recommend adding steps to the unformatted files as these are smaller.

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

Addresses #5 (partial) and #115.

Includes a simple function to save the xarray data to a netcdf, as well as a test reference case to the test data.  Note: does not include metadata, which will be handled in 0.3.0.  

Since `pysatModels` requires more than two data points for testing there, this effectively closes #115 as well.  Updates to tests to finish this out.

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

via pytest

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by jklenzing** [comment]
@aburrell, I've added the benchmark test case to this branch as we discussed for `pysatModels`.  Let me know if this is sufficient to finish out the docs there.

**Comment by jklenzing** [comment]
TODO: change to 5 data points.  Can combine with #115.

**Comment by jklenzing** [comment]
Note: caps imposed for numpy 1.15 version.  NEP 029 only requires support through July 23.  A test branch with numpy 1.16 as the minimum passes without any caps.

https://travis-ci.com/github/sami2py/sami2py/builds/174523684

**Comment by aburrell** [comment]
Something I belatedly noticed:  after running the tests I have two files that have not been removed after testing and are not ignored by .gitignore: 

1. $GITDIR/sami2py/sami2py/fortran/exb.inp
2. $GITDIR/sami2py/sami2py/fortran/sami2py-1.00.namelist

**Comment by jklenzing** [comment]
This is a recurring issue for local tests.  I generally just delete changes to these afterward.  They should be ignored by .gitignore in theory, but I've had issues in running the code if they are.

**Comment by aburrell** [comment]
You know you can have the tests delete them, right?

**Comment by jklenzing** [comment]
I'll poke into this some more.  The issue I ran into in the past was that if the files don't exist at all, some of the code wouldn't initialize.  Worth trying to solve though.

**Comment by jklenzing** [comment]
This is partially tied to #68.

**Comment by jklenzing** [comment]
#118 cleans this issue up so that these aren't committed to the repository.

**Pull request merged**
