### PR TITLE
STY: deprecate non-snake_case  keywords

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

Addresses #150

Some fo the keywords for the core class are not snake case.  This updates that, as well as scans for old usage to throw a deprecation warning.

## Type of change

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality
      to not work as expected)

# How Has This Been Tested?

Usage of old kwargs should throw a deprecation warning
```
import sami2py
sami2py.run_model(tag='test', hrmax=0.0, Tinf_scale=0.7)
```

Uasge of new kwargs will run as expected
```
import sami2py
sami2py.run_model(tag='test', hrmax=0.0, tinf_scale=0.7)
```

Using hrmax=0 keeps the run to a minimum.  The namelist can be inspected to ensure the kwargs are passed through correctly.

**Test Configuration**:
* Mac OS X Big Sur
* Python 3.8.11

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Review by JonathonMSmith — COMMENTED** [review]
In test_core, some functions like test_run_model_ExB_files are still using the camelCase keywords. see test_core.py line 100. Are we waiting to change this until the deprecation warnings are versioned out?

**Comment by jklenzing** [comment]
> In test_core, some functions like test_run_model_ExB_files are still using the camelCase keywords. see test_core.py line 100. Are we waiting to change this until the deprecation warnings are versioned out?

Good catch.  We should take care of this here.

**Comment by jklenzing** [comment]
There's an issue with the latest xarray (2022.6) and numpy 1.20.  Not sure what is going on, but it results not being able to collect unit tests.  Installing a known working version for the NEP29 tests, which seems to work. This can be re-evaluated when numpy 1.20 is dropped Jan 2023.

**Review by JonathonMSmith — APPROVED** [review]

**Comment by jklenzing** [comment]
> There's an issue with the latest xarray (2022.6) and numpy 1.20. Not sure what is going on, but it results in pytest not being able to collect unit tests. Installing a known working version for the NEP29 tests, which seems to work. This can be re-evaluated when numpy 1.20 is dropped Jan 2023.

Lining to issue at xarray for reference: https://github.com/pydata/xarray/issues/6818

**Pull request merged**
