### PR TITLE
BUG/TST: github actions Mac support

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

Addresses #149 

Fixes a bug when using github actions for macosx.  Requires a reinstall of gcc in the GA environment.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

via Github Actions

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by jklenzing** [comment]
@JonathonMSmith, I'm not sure why the windows tests are suddenly broken.  Any ideas?

**Comment by JonathonMSmith** [comment]
> Is fortran being installed on the windows machine?

well it looks like gfortran is include on windows

**Comment by jklenzing** [comment]
Looks like it's a github actions update that broke things:

| | working | broken |
|---|---|---|
| runner version | 2.293.0| 2.294.0 |
| environment | windows-2022 | windows-2022 |
| version | 20220614.0 | 20220626.1 |

**Comment by JonathonMSmith** [comment]
Just to add confirmation for that. I just cloned, installed, and successfully ran all of the tests in windows 10 with python 3.9

**Comment by jklenzing** [comment]
Haven't finished comparing the changes yet, but I'm going to guess it the update to Mingw-w64

**Comment by jklenzing** [comment]
#166 fixes the windows issues.  That should be merged into this one.

**Comment by jklenzing** [comment]
Merged and ready for review, @JonathonMSmith

**Review by JonathonMSmith — APPROVED** [review]

**Pull request merged**
